#datetime: 2023-03-12T09:57:09 #format: 2023-03-12T09:57:38 or now
datetime: 2023-12-5T10:59:20 #format: 2023-03-12T09:57:38 or now
source: video_frame #source
frame_skip: 1 #number of frame skipping
save_preview: True #save as video

main_model_path: "weights/yolov8l.pt"
dimsum_model_path: "weights/205trainset_400epoch_model_S.pt"
drawer_model_path: "weights/drawer_open_300Epoch_model_S.pt"
save_customer_path_parent: "/djangoAPP"
save_customer_path_child: "/mock_media/customer"

save_preview_path: "result_video/ver_1.mp4" #unusable

video_frame:
  source: video
  simulate: True # False = read 100% , True = sampling
  url: "inference/videos/2hr_restaurant.mp4"

live_frame:
  source: live_frame
  url: "http://10.0.1.1:8080/"

save_vid_period: 1

#color in BGR
colors:
  unknown:
    - 102
    - 0
    - 204
  customer:
    - 255
    - 0
    - 102
  employee:
    - 204
    - 204
    - 0

table_coordinate:
  pts1:
    - [83, 217]
    - [334, 124]
    - [476, 272]
    - [148, 430]
    - [113, 318]
  pts2:
    - [146, 431]
    - [479, 272]
    - [711, 530]
    - [279, 745]
    - [207, 575]
  pts3:
    - [442, 0]
    - [710, 0]
    - [710, 60]
    - [520, 115]
    - [442, 73]
  pts4:
    - [710, 0]
    - [1040, 0]
    - [1040, 108]
    - [876, 163]
    - [710, 60]
  pts5:
    - [956, 136]
    - [1237, 17]
    - [1548, 184]
    - [1340, 370]
    - [1110, 228]
  pts6:
    - [1629, 195]
    - [1920, 321]
    - [1920, 530]
    - [1739, 440]
    - [1531, 318]

table_crop_coord:
  pts1:
    - [119, 193]
    - [430, 193]
    - [430, 347]
    - [119, 347]
  pts2:
    - [220, 364]
    - [683, 364]
    - [683, 633]
    - [220, 633]
  pts3:
    - [442, 0]
    - [730, 0]
    - [730, 67]
    - [442, 67]
  pts4:
    - [708, 0]
    - [1012, 0]
    - [1012, 118]
    - [708, 118]
  pts5:
    - [1042, 110]
    - [1445, 110]
    - [1445, 298]
    - [1042, 298]
  pts6:
    - [1709, 307]
    - [1911, 307]
    - [1911, 452]
    - [1709, 452]

table_coord_for_recording:
  pts1:
    - [41, 126]
    - [456, 429]
  pts2:
    - [134, 286]
    - [718, 721]
  pts3:
    - [433, 0]
    - [759, 189]
  pts4:
    - [683, 0]
    - [1093, 255]
  pts5:
    - [993, 0]
    - [1598, 509]
  pts6:
    - [1543, 127]
    - [1920, 666]

drawer_coordination:
  pts1:
    - [372, 808]
    - [869, 1080]

cashier_detect_area:
  pts1:
    - [396, 745]
    - [857, 1080]

cashier_record_area:
  pts1:
    - [258, 562]
    - [857, 1080]

employee_detect_area:
  pts1:
    - [322, 144]
    - [384, 115]
    - [512, 250]
    - [430, 291]
  pts2:
    - [463, 297]
    - [571, 246]
    - [813, 465]
    - [667, 557]
  pts3:
    - [526, 0]
    - [676, 0]
    - [679, 68]
    - [552, 114]
  pts4:
    - [712, 25]
    - [900, 155]
    - [808, 221]
    - [634, 112]
  pts5:
    - [974, 144]
    - [1228, 290]
    - [1150, 384]
    - [894, 266]
  pts6:
    - [1604, 313]
    - [1910, 474]
    - [1910, 630]
    - [1550, 409]

employee_record_area:
  pts1:
    - [41, 0]
    - [456, 429]
  pts2:
    - [134, 160] #width = 584, height = 561 size =  (377, 539)
    - [718, 721]
  pts3:
    - [463, 0]
    - [759, 189]
  pts4:
    - [683, 0]
    - [1093, 255]
  pts5:
    - [993, 0]
    - [1598, 509]
  pts6:
    - [1543, 127]
    - [1920, 666]
