datetime: 2023-03-12T09:57:09 #format: 2023-03-12T09:57:38 or now

main_model_path: "weights/yolov8l.pt"
dimsum_model_path: "weights/205trainset_400epoch_model_S.pt"
drawer_model_path: "weights/drawer_open_300Epoch_model_S.pt"
save_customer_path_parent: "/djangoAPP"
save_customer_path_child: "/mock_media/customer"

save_preview: False
save_preview_path: "result_video/processing_record2.mp4"

source: video_frame
frame_skip: 1

video_frame:
  source: video
  simulate: True
  url: "inference/videos/restaurant_test_human_inout_cashier_2round_with_drawer.mp4"

live_frame:
  source: live_frame
  url: 0

save_vid_period: 1

#color in BGR
colors:
  unknown:
    - 102
    - 0
    - 204
  customer:
    - 255
    - 0
    - 102
  employee:
    - 204
    - 204
    - 0

table_coordinate:
  pts1:
    - [90, 245]
    - [318, 145]
    - [427, 294]
    - [148, 430]
    - [113, 318]
  pts2:
    - [148, 436]
    - [449, 302]
    - [660, 566]
    - [279, 745]
    - [207, 575]
  pts3:
    - [472, 0]
    - [709, 0]
    - [709, 60]
    - [550, 115]
    - [472, 73]
  pts4:
    - [710, 0]
    - [1040, 0]
    - [1040, 108]
    - [876, 163]
    - [710, 60]
  pts5:
    - [986, 136]
    - [1267, 17]
    - [1578, 184]
    - [1370, 370]
    - [1140, 228]
  pts6:
    - [1685, 220]
    - [1920, 321]
    - [1920, 530]
    - [1739, 440]
    - [1596, 355]

table_crop_coord:
  pts1:
    - [119, 193]
    - [430, 193]
    - [430, 347]
    - [119, 347]
  pts2:
    - [220, 364]
    - [683, 364]
    - [683, 633]
    - [220, 633]
  pts3:
    - [492, 0]
    - [700, 0]
    - [700, 67]
    - [492, 67]
  pts4:
    - [708, 0]
    - [1012, 0]
    - [1012, 118]
    - [708, 118]
  pts5:
    - [1042, 110]
    - [1445, 110]
    - [1445, 298]
    - [1042, 298]
  pts6:
    - [1709, 307]
    - [1911, 307]
    - [1911, 452]
    - [1709, 452]

table_coord_for_recording:
  pts1:
    - [41, 126]
    - [456, 429]
  pts2:
    - [134, 286]
    - [718, 721]
  pts3:
    - [463, 0]
    - [759, 189]
  pts4:
    - [683, 0]
    - [1093, 255]
  pts5:
    - [993, 0]
    - [1598, 509]
  pts6:
    - [1543, 127]
    - [1920, 666]

drawer_coordination:
  pts1:
    - [372, 808]
    - [869, 1080]

cashier_detect_area:
  pts1:
    - [396, 745]
    - [857, 1080]

cashier_record_area:
  pts1:
    - [258, 562]
    - [857, 1080]

employee_detect_area:
  pts1:
    - [322, 144]
    - [384, 115]
    - [512, 250]
    - [430, 291]
  pts2:
    - [463, 297]
    - [571, 246]
    - [813, 465]
    - [667, 557]
  pts3:
    - [526, 0]
    - [676, 0]
    - [679, 68]
    - [552, 114]
  pts4:
    - [712, 25]
    - [900, 155]
    - [808, 221]
    - [634, 112]
  pts5:
    - [974, 144]
    - [1228, 290]
    - [1150, 384]
    - [894, 266]
  pts6:
    - [1604, 313]
    - [1910, 474]
    - [1910, 630]
    - [1550, 409]

employee_record_area:
  pts1:
    - [41, 0]
    - [456, 429]
  pts2:
    - [134, 160] #width = 584, height = 561 size =  (377, 539)
    - [718, 721]
  pts3:
    - [463, 0]
    - [759, 189]
  pts4:
    - [683, 0]
    - [1093, 255]
  pts5:
    - [993, 0]
    - [1598, 509]
  pts6:
    - [1543, 127]
    - [1920, 666]
