source: video_frame
frame_skip: 1

video_frame:
  source: video
  url: "inference/videos/restaurantFull.mp4"

live_frame:
  source: live_frame
  url: 0

table_coordinate:
  pts1:
    - [90, 245]
    - [318, 145]
    - [427, 294]
    - [148, 430]
    - [113, 318]
  pts2:
    - [148, 436]
    - [449, 302]
    - [660, 566]
    - [279, 745]
    - [207, 575]
  pts3:
    - [472, 0]
    - [709, 0]
    - [709, 60]
    - [550, 115]
    - [472, 73]
  pts4:
    - [710, 0]
    - [1040, 0]
    - [1040, 108]
    - [876, 163]
    - [710, 60]
  pts5:
    - [986, 136]
    - [1267, 17]
    - [1578, 184]
    - [1370, 370]
    - [1140, 228]
  pts6:
    - [1685, 220]
    - [1920, 321]
    - [1920, 530]
    - [1739, 440]
    - [1596, 355]
