path: /Users/Sukri/Desktop/trainDimsum/datasets/dimsum # dataset root dir
train: images/train # train images (relative to 'path') 4 images
val: images/val # val images (relative to 'path') 4 images

# Classes (80 COCO classes)
names:
  0: dimsum
