source: video_frame
frame_skip: 1

video_frame:
  source: video
  url: "inference/videos/occupied_test_full.mp4"

live_frame:
  source: live_frame
  url: 0

table_coordinate:
  pts1:
    - [90, 245]
    - [318, 145]
    - [427, 294]
    - [148, 430]
  pts2:
    - [148, 436]
    - [449, 302]
    - [660, 566]
    - [279, 745]
  pts3:
    - [460, 0]
    - [700, 0]
    - [716, 104]
    - [515, 155]
  pts4:
    - [707, 44]
    - [827, 0]
    - [1090, 60]
    - [842, 152]
  pts5:
    - [986, 136]
    - [1267, 17]
    - [1578, 184]
    - [1370, 370]
  pts6:
    - [1622, 192]
    - [1920, 321]
    - [1920, 666]
    - [1578, 486]
